trigger:
- main

pool: k8s


stages:
  - stage: buildstsge
    jobs:
      - job: buildjob
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'acr connection'
              repository: 'indexfile'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'manifests'
              publishLocation: 'Container'
## Deploy stage
  - stage: deployStage
    jobs:
    - deployment: deploy 
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
            - download: current
              artifact: manifests
            - task: KubernetesManifest@1 
              inputs:
                action: 'deploy'
                connectionType: 'kubernetesServiceConnection'
                kubernetesServiceConnection: 'k8s connection'
                namespace: 'default'
                manifests: |
                  $(System.DefaultWorkingDirectory)\manifests\deploy1.yaml  
                  $(System.DefaultWorkingDirectory)\manifests\svc1.yaml
                containers: |
                  himalay.azurecr.io/indexfile:$(Build.BuildId)
        
          
