apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1
  labels: 
    app: myproject1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject1
  template: 
    metadata:
      labels:
        app: myproject1
    spec:       
      containers:
      - image: himalay.azurecr.io/indexfile:latest
        imagePullPolicy: Always
        name: deploy-con
        ports:
        - containerPort: 80 
